name: gyro_car
description: A Flutter application to control a car using gyroscope data.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^6.1.1  # For gyroscope data
  flutter_bluetooth_serial_2: ^4.0.0  # For Bluetooth Classic (ESP32 compatible)
  shared_preferences: ^2.2.2  # For saving settings
  provider: ^6.1.1  # For state management
  cupertino_icons: ^1.0.6
  flutter_mjpeg: ^2.0.4
  permission_handler: ^11.0.1  # For handling runtime permissions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
